name: Build and Deploy

on:
  push:
    branches:
      - workflow
  pull_request:
    branches:
      - workglow

jobs:
  app-and-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # or 21

      - name: Install WiX Toolset (required for jpackage on Windows)
        run: |
          choco install wixtoolset -y

      - name: Download gson jar
        run: |
          mkdir vendor
          curl -L -o vendor\gson-2.10.1.jar https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar

      - name: Compile Java module
        run: |
          mkdir mods\kentekencheck
          dir /s /b *.java > sources.txt
          javac -d mods\kentekencheck ^
            --module-path vendor\gson-2.10.1.jar ^
            --add-modules com.google.gson ^
            --add-reads kentekencheck=ALL-UNNAMED ^
            @sources.txt

      - name: Create JAR
        run: |
          mkdir build
          jar --create ^
            --file=build\output.jar ^
            --module-version=1.0 ^
            -C mods\kentekencheck .

      - name: Run jpackage
        run: |
          jpackage @pack.jpack
