name: Build and Deploy

on:
  push:
    branches:
      - workflow
  pull_request:
    branches:
      - workglow

jobs:
  app-and-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # or 21

      - name: Install WiX Toolset (required for jpackage on Windows)
        run: |
          choco install wixtoolset -y

      - name: Download gson jar
        run: |
          curl -L -o vendor\gson-2.10.1.jar https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar

      - name: Compile Java module
        run: |
          mkdir mods\kentekencheck
          javac -d mods/kentekencheck --module-path "vendor\gson-2.10.1.jar" --add-modules com.google.gson --add-reads kentekencheck=ALL-UNNAMED (Get-ChildItem -Recurse -Filter *.java).FullName

      - name: Create JAR
        run: |
          jar --create --file=build/output.jar --module-version=1.0 -C mods/kentekencheck .

      - name: Run jpackage
        shell: cmd
        run: |
          jpackage @pack.jpack
          
       - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kentekencheck
          path: build/kentekencheck-1.0.exe
